### ISSUE TITLE
Python 2.7.6 Django 1.7 Can't run createinitialfieldhistory command

### ISSUE THREAD

**Issue by infinitedreams9586** [grantmcconnaughey/django-field-history#26]
$ ./manage.py createinitialfieldhistory
Traceback (most recent call last):
  File "src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/mdm/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/mdm/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/mdm/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 272, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/vagrant/mdm/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 75, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/vagrant/mdm/env/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/home/vagrant/mdm/env/local/lib/python2.7/site-packages/field_history/management/commands/createinitialfieldhistory.py", line 4, in <module>
    from django.apps import apps
ImportError: No module named apps

**Comment by richtier** [comment]
the package does not claim to support django 1.7

https://github.com/grantmcconnaughey/django-field-history/blob/master/setup.py#L63
